name: Keep Streamlit App Awake

    on:
      schedule:
        # Runs at 00:00 every 3rd day to reset the 7-day timer
        - cron: '0 0 */3 * *'
      workflow_dispatch: # Allows you to trigger it manually if needed

    jobs:
      ping:
        runs-on: ubuntu-latest
        steps:
          - name: Ping Streamlit App
            run: curl -sL https://ward-council-assignments.streamlit.app > /dev/null
